import React, { useState } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Alert,
  ActivityIndicator,
  Platform,
} from "react-native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { RootStackParamList } from "../src/types/game.types";
import { authenticateDevice, getSocket, getOnlinePlayers, getPendingChallenges } from "../src/services/nakama";
import { nakamaClient } from "../src/services/nakama/client";
import { useStore } from "../src/store";
import * as Application from "expo-application";

type Props = {
  navigation: NativeStackNavigationProp<RootStackParamList, "Home">;
};

export default function HomeScreen({ navigation }: Props) {
	const [loading, setLoading] = useState(true);
	const { setAuth, username: storeUsername, setOnlinePlayers, setPendingChallenges } = useStore();

  React.useEffect(() => {
    async function autoLogin() {
      try {
        let deviceId: string | null = null;
        if (Platform.OS === "android") {
          deviceId = Application.getAndroidId();
        } else if (Platform.OS === "ios") {
          deviceId = await Application.getIosIdForVendorAsync();
        } else {
          deviceId = `device-${Math.random().toString(36).substring(2)}`;
        }

        const session = await authenticateDevice(deviceId ?? `device-${Date.now()}`, "");
        // Fetch the account to get the true username (either previous or auto-generated by Nakama)
        const profile = await nakamaClient.getAccount(session);
        const autoName = profile.user?.display_name || profile.user?.username || "Player";
        
        setAuth(session.user_id ?? "", autoName, deviceId ?? "");

				// CONNECT SOCKET IMMEDIATELY! This makes the player appear in the online list for others.
				await getSocket();

				// IMMEDIATELY FORCE A GLOBAL HEARTBEAT & SYNC
				const pingSocialData = async () => {
					try {
						const [players, challenges] = await Promise.all([
							getOnlinePlayers(),
							getPendingChallenges(),
						]);
						setOnlinePlayers(players);
						setPendingChallenges(challenges);
					} catch (e) {
						// Socket may naturally drop if switching networks
					}
				};

				// Do it once now, and then loop forever!
				pingSocialData();
				setInterval(pingSocialData, 5000);

			} catch (err) {
				console.error("Auto login failed", err);
				Alert.alert("Connection failed", "Make sure your server is running and your IP in nakama.config.ts is right.");
			} finally {
				setLoading(false);
			}
		}

		autoLogin();
	}, [setAuth, setOnlinePlayers, setPendingChallenges]);

  async function handlePlay() {
    navigation.navigate("Matchmaking");
  }

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Tic Tac Toe</Text>
      <Text style={styles.subtitle}>Multiplayer</Text>

      <View style={styles.card}>
        <Text style={styles.label}>Welcome back</Text>
        <Text style={styles.usernameDisplay}>
          {loading ? "Connecting..." : storeUsername}
        </Text>
        <Text style={styles.subtext}>You can change this in your Profile</Text>

        <TouchableOpacity
          style={[styles.button, loading && styles.buttonDisabled]}
          onPress={handlePlay}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.buttonText}>Find Match</Text>
          )}
        </TouchableOpacity>
      </View>

      <TouchableOpacity
        style={styles.leaderboardBtn}
        onPress={() => navigation.navigate("Leaderboard")}
      >
        <Text style={styles.leaderboardText}>🏆 Leaderboard</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f0f1a",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  title: {
    fontSize: 42,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: -1,
  },
  subtitle: {
    fontSize: 16,
    color: "#555",
    marginBottom: 48,
    letterSpacing: 4,
    textTransform: "uppercase",
  },
  card: {
    backgroundColor: "#1a1a2e",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    borderWidth: 1,
    borderColor: "#2a2a4a",
  },
  label: {
    color: "#888",
    fontSize: 13,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  usernameDisplay: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
  },
  subtext: {
    color: "#555",
    fontSize: 12,
    marginBottom: 24,
  },
  button: {
    backgroundColor: "#6c63ff",
    borderRadius: 12,
    padding: 18,
    alignItems: "center",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
  },
  leaderboardBtn: {
    marginTop: 32,
    padding: 12,
  },
  leaderboardText: {
    color: "#6c63ff",
    fontSize: 16,
    fontWeight: "600",
  },
});